import { useEffect, useState } from "react";

/** One controlled-vocabulary term: name + (optional) definition. */
export type CvTerm = { n: string; d?: string };
export type CvMap = Record<string, CvTerm>;

// The term map (PSI-MS + Unit + Imaging-MS, generated by scripts/gen-cv-terms.mjs)
// is ~150 kB gzipped, so it's loaded lazily as its own chunk the first time a CV
// accession needs a label — never on initial app load.
let resolved: CvMap | null = null;
let pending: Promise<CvMap> | null = null;

export function loadCvTerms(): Promise<CvMap> {
  if (resolved) return Promise.resolve(resolved);
  if (!pending) {
    pending = import("../data/cv-terms.json").then((m) => {
      resolved = (m.default ?? m) as CvMap;
      return resolved;
    });
  }
  return pending;
}

/** Trigger the lazy load and re-render once the term map is available. */
export function useCvTerms(): CvMap | null {
  const [map, setMap] = useState<CvMap | null>(resolved);
  useEffect(() => {
    if (map) return;
    let alive = true;
    void loadCvTerms().then((m) => alive && setMap(m));
    return () => {
      alive = false;
    };
  }, [map]);
  return map;
}

// Trailing (?!\d) instead of \b: in the promoted-column form "MS_1000511_ms_level"
// the digits are followed by "_" (a word char), so \b would fail to match.
const ACCESSION = /\b(MS|IMS|UO|PEFF|BTO|NCIT|PRIDE)[:_](\d{4,7})(?!\d)/;
const BARE_ACCESSION = /^(MS|IMS|UO|PEFF|BTO|NCIT|PRIDE):\d{4,7}$/;

/** Extract the first CV accession from a string (handles "MS:1000511" and the
 *  promoted-column "MS_1000511_…" underscore form), normalized to "MS:1000511". */
export function accessionIn(text: string): string | null {
  const m = ACCESSION.exec(text);
  return m ? `${m[1]}:${m[2]}` : null;
}

export function isBareAccession(text: string): boolean {
  return BARE_ACCESSION.test(text);
}

/** Tooltip text for an accession: "MS:1000511 · ms level — <definition>". */
export function cvTitle(map: CvMap | null, accession: string | null): string | undefined {
  if (!map || !accession) return undefined;
  const t = map[accession];
  if (!t) return undefined;
  return t.d ? `${accession} · ${t.n} — ${t.d}` : `${accession} · ${t.n}`;
}

/** Term name for an accession, or null if unknown. */
export function cvName(map: CvMap | null, accession: string | null): string | null {
  if (!map || !accession) return null;
  return map[accession]?.n ?? null;
}
