// GOLDEN: dual-stored fixture (every spectrum present BOTH as profile in spectra_data
// AND centroided in spectra_peaks — generated by test/fixtures/gen_dual.py). Guards the
// Signal-source toggle end-to-end through the REAL reader:
//  - Auto routing follows the DECLARED representation per spectrum (the fixture mixes
//    declarations precisely so a swapped-facet router cannot pass — review finding),
//  - forcing each source returns that facet's distinct arrays with truthful sourceUsed,
//  - altAvailable is true, and the declared representation is never rewritten.
import { describe, it, expect, beforeAll } from "vitest";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { openEngineFile, type EngineFile } from "./open";
import { readEngineSpectrum } from "./spectrum";

const FIXTURE = fileURLToPath(new URL("../../test/fixtures/dual.mzpeak", import.meta.url));
const PROFILE_PTS = 40;
const PEAKS = 5;

describe("DUAL golden: profile+centroid stored for the same spectra", () => {
  let ef: EngineFile;
  beforeAll(async () => {
    const b = await readFile(FIXTURE);
    const ab = b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer;
    ef = await openEngineFile(ab, "dual.mzpeak");
  }, 60000);

  it("opens with 3 spectra", () => {
    expect(ef.stats.numSpectra).toBe(3);
  });

  it("Auto follows the declaration: declared-profile spectrum 0 → profile facet", async () => {
    const s = await readEngineSpectrum(ef.reader, 0);
    expect(s.representation).toBe("profile");
    expect(s.sourceUsed).toBe("profile");
    expect(s.altAvailable).toBe(true);
    expect(s.mz.length).toBe(PROFILE_PTS);
  });

  it("Auto follows the declaration: declared-centroid spectrum 2 → centroid facet", async () => {
    const s = await readEngineSpectrum(ef.reader, 2);
    expect(s.representation).toBe("centroid");
    expect(s.sourceUsed).toBe("centroid");
    expect(s.altAvailable).toBe(true);
    expect(s.mz.length).toBe(PEAKS);
  });

  it("forcing centroid on a declared-profile spectrum returns the peaks facet, declaration unchanged", async () => {
    const s = await readEngineSpectrum(ef.reader, 0, "centroid");
    expect(s.mz.length).toBe(PEAKS);
    expect(s.sourceUsed).toBe("centroid");
    expect(s.representation).toBe("profile"); // declared value NEVER rewritten
  });

  it("forcing profile on a declared-centroid spectrum returns the data facet, declaration unchanged", async () => {
    const s = await readEngineSpectrum(ef.reader, 2, "profile");
    expect(s.mz.length).toBe(PROFILE_PTS);
    expect(s.sourceUsed).toBe("profile");
    expect(s.representation).toBe("centroid");
  });

  it("the two facets are genuinely different arrays (facet sentinels)", async () => {
    const prof = await readEngineSpectrum(ef.reader, 1, "profile");
    const cent = await readEngineSpectrum(ef.reader, 1, "centroid");
    expect(prof.mz.length).not.toBe(cent.mz.length);
    // profile carries the +5 baseline; centroids are the bare 5 peak heights
    expect(Math.min(...Array.from(prof.intensity))).toBeGreaterThan(0);
    expect(cent.intensity.length).toBe(PEAKS);
  });
});
